### ISSUE TITLE
はたなかさんが動かなくなりました、、、、、

### ISSUE THREAD

**Issue by sawa0103** [MugMugCup/welcome-event-2024#1]
寝ている最中に斜め435度でチョップしたら動かなくなっちゃいました、、
再起動もしてみましたが治りません、、、
直せますか？

**Comment by sawa0103** [comment]
これはテストです

**Comment by MugMugCup** [comment]
すみません、それは致命的なエラーですね。
すでに原因は発見したので、次のアップデートでは対策予定です。
ご不便をおかけしますが、ご了承ください。
